spring:
  datasource:
    url: jdbc:mysql://mysql:3306/knowledge_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

dubbo:
  registry:
    address: nacos://nacos:8848

