server:
  port: 8080

spring:
  application:
    name: gateway-service
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

dubbo:
  application:
    name: gateway-service
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: 20880
  config-center:
    address: nacos://localhost:8848
    username: nacos
    password: nacos
    check: true
  metadata-report:
    address: nacos://localhost:8848
    username: nacos
    password: nacos

